export const offersData=
[ { id: 1,
    nomOffers:'Silver',
    price: '59dt',
    calculateurD : 'Calculateur diététique',
    icon:'offer-link-icon-valid fal fa-check',
    calculateurP: 'Calculateur de progression',
    iconP:'offer-link-icon-valid fal fa-check',
    ficheP:'Fiches de suivi (poids, mensurations, sommeil, stress)',
    iconFP:'offer-link-icon-no-valid fal fa-ban',
    book: 'E-BOOK',
    iconB:'offer-link-icon-no-valid fal fa-ban',
    carnetE:'CARNET D’ENTRAINEMENT',
    iconC:'offer-link-icon-no-valid fal fa-ban',
},
{ id: 2,
    nomOffers:'Gold',
    price: '89dt',
    calculateurD : 'Calculateur diététique',
    icon:'offer-link-icon-valid fal fa-check',
    calculateurP: 'Calculateur de progression',
    iconP:'offer-link-icon-valid fal fa-check',
    ficheP:'Fiches de suivi (poids, mensurations, sommeil, stress)',
    iconFP:'offer-link-icon-valid fal fa-check',
    book: 'E-BOOK',
    iconB:'offer-link-icon-no-valid fal fa-ban',
    carnetE:'CARNET D’ENTRAINEMENT',
    iconC:'offer-link-icon-no-valid fal fa-ban',
},
{ id: 3,
    nomOffers:'Gold Plus',
    price: '159dt',
    calculateurD : 'Calculateur diététique',
    icon:'offer-link-icon-valid fal fa-check',
    calculateurP: 'Calculateur de progression',
    iconP:'offer-link-icon-valid fal fa-check',
    ficheP:'Fiches de suivi (poids, mensurations, sommeil, stress)',
    iconFP:'offer-link-icon-valid fal fa-check',
    book: 'E-BOOK',
    iconB:'offer-link-icon-valid fal fa-check',
    carnetE:'CARNET D’ENTRAINEMENT',
    iconC:'offer-link-icon-valid fal fa-check',
}
]